### ISSUE TITLE
Discussion Tab

### ISSUE THREAD

**Issue by jacobxperez** [viT-1/iAMcss#1]
@viT-1 Hey thanks for replying my message back in the [Why has AM not taken off?](https://github.com/amcss/attribute-module-specification/issues/29) issue and I was just wondering if you can open up a discussion tab just to interchange some ideas instead of using the issues tab. However, unless you like using the issues tab, then I can respect that.

**Comment by viT-1** [comment]
@jacobxperez [Welcome](https://github.com/viT-1/iAMcss/discussions/2)!
